services:
  db:
    image: 'postgres:latest'
    environment:
      - 'POSTGRES_DB=storage'
      - 'POSTGRES_PASSWORD=root'
      - 'POSTGRES_USER=root'
    volumes:
      - 'data:/var/lib/postgresql/data'
    ports:
      - '5432:5432'

volumes:
  data:
